var myFirstVar;
var mySecondVar;
var myThirdVar;
var myFourthVar;
var myFifthVar;
var myFirstNumVar	= 1;
var mySecondNumVar	= 2;
var myThirdNumVar	= 3;
var myFourthNumVar	= 4;
var myFifthNumVar	= 5;
var myFirstWordVar	= 'Sam';
var myFirstWordVar	= 'Tom';
var myFirstWordVar	= 'John';
var myFirstWordVar	= 'Kevin';
var myFirstWordVar	= 'Bill';
var hasADog	= true;
var ownsACat	= false;
var hasACar	= true;
var hasAHouse	= false;
var likesToEat	= true;
